/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JavaSwing.Application;

import javax.swing.JOptionPane;

/**
 *
 * @author dell
 */
public class UnitConverter2 extends javax.swing.JFrame {

    /**
     * Creates new form UnitConverter2
     */
    public UnitConverter2() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jp1 = new javax.swing.JPanel();
        jlbl1 = new javax.swing.JLabel();
        jlbl2 = new javax.swing.JLabel();
        jtxt1 = new javax.swing.JTextField();
        txtResult = new javax.swing.JTextField();
        jp2 = new javax.swing.JPanel();
        jrdo1 = new javax.swing.JRadioButton();
        jrdo2 = new javax.swing.JRadioButton();
        jrdo3 = new javax.swing.JRadioButton();
        btnclear = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        jlbl3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp1.setBackground(new java.awt.Color(0, 0, 0));
        jp1.setForeground(new java.awt.Color(255, 51, 51));

        jlbl1.setBackground(new java.awt.Color(255, 255, 255));
        jlbl1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbl1.setForeground(new java.awt.Color(51, 255, 51));
        jlbl1.setText("Enter KM");
        jlbl1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 255, 51)));

        jlbl2.setBackground(new java.awt.Color(255, 255, 255));
        jlbl2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbl2.setForeground(new java.awt.Color(51, 255, 51));
        jlbl2.setText("AFTER CONVERTING");
        jlbl2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 255, 51)));

        jtxt1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 255, 51)));

        txtResult.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 255, 51)));

        jp2.setBackground(new java.awt.Color(255, 255, 255));

        jrdo1.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrdo1);
        jrdo1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrdo1.setForeground(new java.awt.Color(0, 255, 0));
        jrdo1.setText("meter");
        jrdo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdo1ActionPerformed(evt);
            }
        });

        jrdo2.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrdo2);
        jrdo2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrdo2.setForeground(new java.awt.Color(0, 255, 0));
        jrdo2.setText("centimeter");
        jrdo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdo2ActionPerformed(evt);
            }
        });

        jrdo3.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrdo3);
        jrdo3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrdo3.setForeground(new java.awt.Color(0, 255, 0));
        jrdo3.setText("milimeters");
        jrdo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdo3ActionPerformed(evt);
            }
        });

        btnclear.setBackground(new java.awt.Color(0, 0, 0));
        btnclear.setForeground(new java.awt.Color(0, 255, 0));
        btnclear.setText("CLEAR");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        btnexit.setBackground(new java.awt.Color(0, 0, 0));
        btnexit.setForeground(new java.awt.Color(0, 255, 0));
        btnexit.setText("EXIT");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp2Layout = new javax.swing.GroupLayout(jp2);
        jp2.setLayout(jp2Layout);
        jp2Layout.setHorizontalGroup(
            jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2Layout.createSequentialGroup()
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jrdo1)
                        .addGap(62, 62, 62)
                        .addComponent(jrdo2))
                    .addGroup(jp2Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(btnclear)))
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(jrdo3)
                        .addGap(35, 35, 35))
                    .addGroup(jp2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnexit)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jp2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jrdo1, jrdo2, jrdo3});

        jp2Layout.setVerticalGroup(
            jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jrdo1)
                        .addComponent(jrdo2))
                    .addComponent(jrdo3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnclear)
                    .addComponent(btnexit))
                .addContainerGap())
        );

        jp2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jrdo1, jrdo2, jrdo3});

        jlbl3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlbl3.setForeground(new java.awt.Color(51, 255, 51));
        jlbl3.setText("SELECT CONVERTION UNIT");

        javax.swing.GroupLayout jp1Layout = new javax.swing.GroupLayout(jp1);
        jp1.setLayout(jp1Layout);
        jp1Layout.setHorizontalGroup(
            jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlbl1, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(jlbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxt1, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(txtResult))
                .addContainerGap())
            .addComponent(jp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jp1Layout.createSequentialGroup()
                .addComponent(jlbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jp1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jlbl1, jlbl2});

        jp1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jtxt1, txtResult});

        jp1Layout.setVerticalGroup(
            jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jlbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jp1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jlbl1, jlbl2});

        jp1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jtxt1, txtResult});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrdo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdo1ActionPerformed
      try{
        String kmstr=jtxt1.getText();
        int km=Integer.parseInt(kmstr);
        int meter=km*1000;
        txtResult.setText(String.valueOf(meter)+ "meters");
        
        }
      catch(NumberFormatException ex)
      {
          JOptionPane.showMessageDialog(null,"Please Input Digits only","ERROR!",JOptionPane.ERROR_MESSAGE);
      }  
    }//GEN-LAST:event_jrdo1ActionPerformed

    private void jrdo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdo2ActionPerformed
    try{
        String kmstr=jtxt1.getText();
        int km=Integer.parseInt(kmstr);
        long cm=km*100000L;
       txtResult.setText(String.valueOf(cm)+" centimeters");
    }
    catch(NumberFormatException ex)
    {
        JOptionPane.showMessageDialog(null,"please input digits only!","ERROR!",JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jrdo2ActionPerformed

    private void jrdo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdo3ActionPerformed
    try
    {
        String kmstr=jtxt1.getText();
        int km=Integer.parseInt(kmstr);
        long mm=km*1000000L;
        txtResult.setText(String.valueOf(mm)+ " milimeters");
    }
    catch(NumberFormatException ex)
    {
        JOptionPane.showMessageDialog(null,"please input digits only!","ERROR!",JOptionPane.ERROR_MESSAGE);
    }
    
    }//GEN-LAST:event_jrdo3ActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
      jtxt1.setText("");
      txtResult.setText("");
      jtxt1.requestFocus();// TODO add your handling code here:
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
         int ans;
     ans =JOptionPane.showConfirmDialog(null,"Are You Sure?","CLOSE THIS APP!",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
      if(ans==JOptionPane.YES_OPTION)
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btnexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnitConverter2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnitConverter2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnitConverter2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnitConverter2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UnitConverter2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnexit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jlbl1;
    private javax.swing.JLabel jlbl2;
    private javax.swing.JLabel jlbl3;
    private javax.swing.JPanel jp1;
    private javax.swing.JPanel jp2;
    private javax.swing.JRadioButton jrdo1;
    private javax.swing.JRadioButton jrdo2;
    private javax.swing.JRadioButton jrdo3;
    private javax.swing.JTextField jtxt1;
    private javax.swing.JTextField txtResult;
    // End of variables declaration//GEN-END:variables
}
